package com.rationaldata.hoover.exceptions;

public enum ExceptionCodeEnum {
    REQUEST_NULL, COORDS_INVALID, ROOM_SIZE_INVALID, INSTRUCTIONS_REQUIRED, PATCHES_REQUIRED, POSITION_INPUT_NOT_TWO_NUMBERS
}
