package com.rationaldata.hoover.exceptions;

public enum ExceptionCodeEnum {
    REQUEST_NULL, COORDS_INVALID, ROOM_SIZE_INVALID, INSTRUCTIONS_REQUIRED, UNKNWON_INSTRUCTION, INVALID_INSTRUCTION, PATCHES_INVALID
}
